name: build-test

on:
  push:
    branches: [SFML]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release
