name: window workflow

on:
  push:
    branches: [win]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build && cd build
          cmake .. 
          cmake --build . --config Release

      - name: Run
        run: |
          cd bin/Release
          ./Playground.exe
