name: comment

on:
  issues:
    types: [opened]
    branches: [issue-comment]

jobs:
  comment-with-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Dump github context
        shell: bash
        run: echo '${{ toJSON(github.event) }}' | jq
