name: cmake

on:
  push:
    paths-ignore:
      - "README.md"
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "README.md"
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building with cmake
        run: |
          mkdir build
          cd build
          cmake ..
          make
